services:
  nginx:
    image: nginx:1.30.2-alpine
    container_name: nginx
    ports:
      - 80:80
    dns:
      - 8.8.8.8      # Google DNS
      - 1.1.1.1      # Cloudflare DNS
    networks:
      - logging-network
    volumes:
      - /etc/nginx:/etc/nginx
      - /etc/nginx/confd/site.conf:/home/nikolas/projects/for_painter/site.conf
      - /var/log/nginx:/var/log/nginx
      - /home/nikolas/projects/for_painter/html:/usr/share/nginx/html:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256M'
  
  gallery:
    image: nikolavasant/gallery:1.33
    container_name: gallery
    ports:
      - 8000:8000
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

  gallery1:
    image: nikolavasant/gallery:1.37
    container_name: gallery1
    ports:
      - 7999:7999
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery-arthur:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

  gallery2:
    image: nikolavasant/gallery:1.38
    container_name: gallery2
    ports:
      - 7998:7998
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery-magic:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

  gallery3:
    image: nikolavasant/gallery:1.39
    container_name: gallery3
    ports:
      - 7997:7997
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery-fisher:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

  gallery4:
    image: nikolavasant/gallery:1.40
    container_name: gallery4
    ports:
      - 7996:7996
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery-king:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

  gallery5:
    image: nikolavasant/gallery:1.41
    container_name: gallery5
    ports:
      - 7995:7995
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery-king:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

  gallery6:
    image: nikolavasant/gallery:1.42
    container_name: gallery6
    ports:
      - 7994:7994
    networks:
      - logging-network
    volumes:
      - /var/log/apps/gallery-king:/var/log/gallery
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128M'

networks:
  logging-network:
    driver: bridge
