services:
  nginx:
    image: nginx:1.25-alpine
    container_name: web-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Пробрасываем конфигурацию сайта
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      # Пробрасываем фронтенд (HTML, CSS, JS)
      - ./html:/usr/share/nginx/html
      - /home/nikolas/projects/for_painter/alyakinaira.ru/html/nesessary/images:/usr/share/nginx/html/media
      # Тома для работы SSL и Certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    depends_on:
      - gallery
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256M'

  gallery:
    build:
      context: ./app
      dockerfile: gallery.dockerfile
    container_name: gallery-app
    environment:
      - GALLERY_PORT=8000
      - GALLERY_IMAGES_DIR=/app/media
    volumes:
      # УКАЖИ ЗДЕСЬ СВОЙ ПУТЬ К ПАПКЕ С КАРТИНКАМИ НА СЕРВЕРЕ:
      - /home/nikolas/projects/for_painter/alyakinaira.ru/html/nesessary/images:/app/media:ro
      # Логи Flask приложения
      - /var/log/apps/gallery:/var/log/gallery
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256M'
  # Добавляем сервис Certbot для автоматического обновления сертификатов
  certbot:
    image: certbot/certbot
    container_name: certbot-ssl
    volumes:
      - /var/log/letsencrypt:/var/log/letsencrypt
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    # Проверка обновлений каждые 12 часов
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Объявляем именованные тома для сохранения сертификатов
volumes:
  certbot-etc:
  certbot-var:
  webroot:
