apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gallery-media-pvc
  namespace: for-painter
  uid: 0fc04fc8-e346-4748-b62e-079300168191
  resourceVersion: '966453'
  creationTimestamp: '2026-09-18T13:53:32Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"gallery-media-pvc","namespace":"for-painter"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"100Gi"}},"volumeName":"gallery-media-pv"}}
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
  selfLink: /api/v1/namespaces/for-painter/persistentvolumeclaims/gallery-media-pvc
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  conditions:
    - type: Unused
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2026-09-18T14:08:36Z'
      reason: PodUsingPVC
      message: A pod is currently referencing this PVC
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: gallery-media-pv
  volumeMode: Filesystem